apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-springboot-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-springboot
  template:
    metadata:
      labels:
        app: my-springboot
    spec:
      containers:
      - name: backend
        image: linxianer12/java-mypod
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 8080