apiVersion: v1
kind: Service
metadata:
  name: my-springboot-nodeport-service
spec:
  type: NodePort
  selector:
    app: my-springboot
  ports:
  - port: 21555
    targetPort: 8080
    nodePort: 31222

